// *PRODUCTOS
export const AGREGAR_PRODUCTOS = "AGREGAR_PRODUCTOS";
export const AGREGAR_PRESENTACION = "AGREGAR_PRESENTACION";
export const ACTUALIAZAR_CANTPRESENTACION = "ACTUALIAZAR_CANTPRESENTACION";
export const VACIAR_CESTA = "VACIAR_CESTA";
export const SUMAR_SUBTOTALES = "SUMAR_SUBTOTALES";
export const VACIAR_TOTALPEDIDO = "VACIAR_TOTALPEDIDO";
export const ELIMINAR_PRESENTACION = "ELIMINAR_PRESENTACION";
export const AGREGAR_OFERTA = "AGREGAR_OFERTA";
export const ELIMINAR_OFERTA = "ELIMINAR_OFERTA";
export const AGREGAR_COMBO = "AGREGAR_COMBO";
export const ELIMINAR_COMBO = "ELIMINAR_COMBO";
export const SELECCIONAR_LOCAL = "SELECCIONAR_LOCAL";
export const SET_CONFIRMARPEDIDO = "SET_CONFIRMARPEDIDO";
export const AGREGAR_COMBO_TOPPING = "AGREGAR_COMBO_TOPPING";
export const AGREGAR_SALSAS_CONFIG = "AGREGAR_SALSAS_CONFIG";

// *Clientes
export const AGREGAR_CLIENTE = "AGREGAR_CLIENTE";
export const AGREGAR_CLIENTE_TOKEN = "AGREGAR_CLIENTE_TOKEN";
export const AÑADIR_PRECIO_DELIVERY = "AÑADIR_PRECIO_DELIVERY";

// // USUARIOS
// export const OBTENER_USUARIO = "OBTENER_USUARIO";
